tap "homebrew/bundle"
tap "romkatv/powerlevel10k"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "gh"
brew "imagemagick"
brew "lazygit"
brew "mas"
brew "neovim"
brew "node"
brew "powerlevel10k"
brew "ripgrep"
brew "thefuck"
brew "tmux"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
# cask "adguard"
cask "arc"
# cask "bartender"
cask "font-meslo-lg-nerd-font"
# cask "istat-menus"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "kitty"
cask "monitorcontrol"
# cask "obsidian"
cask "raycast"
# cask "slack"
# cask "soundsource"
mas "Fantastical", id: 975937182
mas "Spark", id: 1176895641
mas "Things", id: 904280696
