# tap "1password/tap"
tap "homebrew/bundle"
tap "romkatv/powerlevel10k"
brew "eza"
brew "fd"
brew "gh"
brew "lazygit"
brew "mas"
brew "neofetch"
brew "neovim"
brew "node"
brew "powerlevel10k"
brew "ripgrep"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
# cask "1password"
# cask "adguard"
cask "arc"
# cask "bartender"
# cask "dropbox"
cask "font-meslo-lg-nerd-font"
# cask "istat-menus"
cask "iterm2"
cask "karabiner-elements"
# cask "keyboardcleantool"
# cask "logi-options+"
# cask "microsoft-auto-update"
# cask "microsoft-edge"
# cask "microsoft-excel"
# cask "microsoft-powerpoint"
# cask "microsoft-word"
# cask "monitorcontrol"
# cask "obsidian"
cask "raycast"
# cask "slack"
# cask "soundsource"
# cask "visual-studio-code"
# mas "Fantastical", id: 975937182
# mas "Spark", id: 1176895641
# mas "Things", id: 904280696
